### ISSUE TITLE
Problem running in Electron

### ISSUE THREAD

**Issue by GordonJones** [mar10/jquery-ui-contextmenu#128]
I am attempting to port my "greens" app to Electron. "greens" uses Fancytree and ui-contextmenu.

I have had a lot of issues with jQuery and node.js porting it across, and have had to adapt some things to make it work.

I have the following failure in ui-contextmenu. It is entirely possible this is my fault, and I need to make some changes, but I am stuck and don't know where to go. This may well be a versioning issue - I am using npm "latest" for all the imported modules. It may also be an issue with your embedded jQuery-ui code. I have had to remove some `button()` calls in my HTML. These worked when using the browser and remote html, but are not recognised in the local HTML. If you have any suggestions, they would be very welcome.

```
Uncaught TypeError: this.$menu.hide(...).addClass(...).menu is not a function
    at $.(anonymous function).(anonymous function)._createUiMenu (/Users/gordon/Desktop/develop/myApp/greens/node_modules/ui-contextmenu/jquery.ui-contextmenu.js:169:5)
    at $.(anonymous function).(anonymous function)._createUiMenu (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:144:25)
    at $.(anonymous function).(anonymous function)._create (/Users/gordon/Desktop/develop/myApp/greens/node_modules/ui-contextmenu/jquery.ui-contextmenu.js:108:8)
    at $.(anonymous function).(anonymous function)._create (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:144:25)
    at $.(anonymous function).(anonymous function)._createWidget (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:341:8)
    at new $.(anonymous function).(anonymous function) (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:99:9)
    at HTMLTableElement.<anonymous> (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:281:30)
    at Function.each (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery/dist/jquery.js:354:19)
    at jQuery.fn.init.each (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery/dist/jquery.js:189:17)
    at jQuery.fn.init.$.fn.(anonymous function) [as contextmenu] (/Users/gordon/Desktop/develop/myApp/greens/node_modules/jquery.fancytree/dist/modules/jquery.fancytree.ui-deps.js:273:9)
```

My app can be found at:
[https://github.com/GordonJones/greens](url)

To run it:
extract the repo.
cd to top level directory
npm install
npm start

I start the chrome devtools on window start up.

**Comment by mar10** [comment]
I did not investigate much, but using jQuery UI in electron seems not to be straight forward:
https://stackoverflow.com/q/34485506/19166
I it is probably possible, but maybe it's easier to switch to another context menu instead. I think jQuery UI doesn't have a bright future anyway.

(Note that Fancytree uses a very small subset of jQuery UI, like the widget framework and some tools, but I try to hide that in a vendored jquery.fancytree.ui-deps.js)
